Updated README.

diff --git a/README b/README
--- a/README
+++ b/README
@@ -1,26 +1,66 @@
-Oh is a Unix shell written in Go.  Like the rc shell, oh is similar in spirit
+﻿Oh is a Unix shell written in Go.  Like the rc shell, oh is similar in spirit
 but different in detail from other Unix shells.
 
-The following commands behave as expected:
+Oh extends the shell's programming language features without sacrificing the
+shell's interactive features. The following commands behave as expected:
 
-date
-cat /usr/share/dict/words
-who >user.names
-who >>user.names
-wc <file
-echo [a-f]*.c
-who | wc
-who; date
-cc *.c &
-mkdir junk && cd junk
-cd ..
-rm -r junk || echo "rm failed!"
+    date
+    cat /usr/share/dict/words
+    who >user.names
+    who >>user.names
+    wc <file
+    echo [a-f]*.c
+    who | wc
+    who; date
+    cc *.c &
+    mkdir junk && cd junk
+    cd ..
+    rm -r junk || echo "rm failed!"
 
-Oh adds support for concurrent, object-based and higher-order programming. See
-using.oh and the sample scripts in the examples directory for more details.
+Oh has objects but no classes. Objects can be created from scratch using the
+'object' command. Private members are defined using the 'define' command and
+public members are defined using the 'public' command:
 
-To compile and run oh you will need go-tecla:
+    define point: object {
+        define x: integer 0
+        define y: integer 0
 
-   github.com/michaelmacinnis/go-tecla
+        public move: method a b {
+            set $self::x: add $self::x a
+            set $self::y: add $self::y b
+        }
+
+        public show: method {
+            echo $self::x $self::y
+        }
+    }
+
+Objects can also be created by cloning an existing object:
+
+    define o: point::clone
+
+Modules are objects. The command below creates an object called 'm'. Public,
+top-level definitions in 'file' can be accessed using the object 'm'.
+
+    define m: import file
+
+Channels are objects. Oh exposes channels, which are implicit in other shells
+in the form of pipes, as first-class values. Channels can be created with the
+'channel' command:
+
+    define c: channel
+
+Oh incorporates many features, including first-class functions from the
+Scheme dialect of Lisp. Like Lisp, oh uses the same syntax for data and code.
+When data is sent across a channel it is converted to text so that it can be
+sent to (or even through) external Unix programs.
+
+To compile and run oh you will need to goinstall go-tecla:
+
+    goinstall github.com/michaelmacinnis/go-tecla
+
+and install (./configure; make install) the C library libtecla:
+
+    http://www.astro.caltech.edu/~mcs/tecla/libtecla.tar.gz
 
 Oh is released under an MIT-style license.
